sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - npm install -g karma-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - karma start karma.conf-ci.js
env:
  global:
    - secure: "J0n8emmbolaH30qGXXE2pxmWQWE90to0x8f3lKmJ6es9E2zpg3BqDe7bziAxRvH8r5MePYrgL2OFQklmNq+NTm60tbTVEmjhaQt5D+MLIwVRyVaMrkj52k5ag/8gcBbXiOqFPAzyFSxUITqVfsz277+cKn/PxVaLb4paUlQgWoT2ZaTnnbsv9w8ytId0pbXXnU54V6InNMsSXzEgrX7pt/NeBT+MfmwmZfap+cwC//Zgl1pF/Z3YLyKw0Qog21qfZ+s5FGKiRQ4GP8X46p/C9yd7RjWCzlNKwKxDgLCWM8rKdI7jUsu2VPZXE5WYkzN0AVx+EncidGJNnZqIGHr4Yn0HaUK9l2GGOcLfVs4FSY8hHjEeIyzyssm8cpggdfYZvSh+tklhG64H6qZ7mNAORD6Mw32GNpdx0xPpjnSOC4CFWE2iobiQsEZt93r9n/FN1TLCFun6rLHcxe3VZOOCXz2DJ/ghhLYwUUvV71ngyPgQx7gv2jSdA9E7MUrpbhGMrTZYR+LAJWwhO50S4LWouokA5bTEEzFfaX0VE0DCFHqpzXRX8KgyI1k5cGS4gucSjvcL8R4YWpMacoJyeS5IYFhoKTGX/Mut70irZeFTrJVJU5OVM+V1xUvfaHTAMo2aMiL6cRug6FFbX+9VZcKqcszunxCh8IENcUSMH7jokLo="
    - secure: "k3Q8Y/B+ZVFRwMD8J9OVZwFvGRy75rILY1swvmGbwRv5nXyyN2bymQf9D7+/VShAvMoiCHIhieRJYIYl0SAO2oe4MsYh7QyzuQiqY0DTfVzGcxvjfeC8TS6zTWYwwDPrTVz35ff+a+L4lZQwet6oenOKV9mkmoPpEUkDVwa8QMyo3zCex4iyvL5xfsYGld6K4X2ttn/LVddOnH4ELRWExG16re0W4fy+T9cqrq+ylDo2uSk+10iGs1yGvDV63FqDOYqcry7uJLqRkLDU3mHnwT/hTkcKlPUIb7lmV2/innb5dJ5ojHBvZZfdS66mC0QIET+KxQWFxN0gap2jIW2wjA7AzVAWbqryyNYUwtODpw9f9eJ4y5MW5kgXkelgveCdA1jjQochm2XTKuj2dajZluVs7DUK7qUNqN3Gvce/QV4xbsnJq6pC76dpqukYYbXVvUdgGXd1Ji8BcgCmWexEKe4//JDVSYGe0Dbjl+lJUUDYU+3eobaheOg1icTwBVuJ6YqtYE7X7v65G4tFpzaJDJWYnCYrSsdKK+5Jk20+ZywcbRkwQlo+lwJXcdPaW2aY99KvLlpvOnoCjuHfskbVdv4HtV+nWiLaVqJvj/L7EpQy0+AnUVUaRxFQmDUFarV0kAumqHpdHtz/TqF0jVVrdCmzb4hXGFTwiJuKJGPtYRo="
addons:
  sauce_connect: true
